name: "activity_recognition"
target_col: "Label"
excluded_labels: []
split_strategy: "kfold"
n_splits: 10
test_video_ids: []

windowing:
  label_specific_rules:
    0:
      window_size: 60
      window_stride: 30
      frame_skip_step: 2
    4:
      window_size: 60
      window_stride: 30
      frame_skip_step: 3
    5:
      window_size: 60
      window_stride: 20
      frame_skip_step: 1
    6:
      window_size: 60
      window_stride: 15
      frame_skip_step: 1
    7:
      window_size: 60
      window_stride: 20
      frame_skip_step: 1
    8:
      window_size: 60
      window_stride: 20
      frame_skip_step: 2

