seed: 42
device: auto

artifacts_dir: artifacts/shared

data:
  window_size: 60
  stride: 30
  batch_size: 32
  sensor_type: "Segment Velocity"
  video_suffix: null
  num_workers: 3
  val_split: 0.2
  participant: "P2" 

model:
  hidden_size: 128
  num_layers: 2

train:
  epochs: 2
  lr: 1e-4
  grad_clip: 1.0
  weight_decay: 1e-5

loss:
  type: auto   # auto | bce | ce

callbacks:
  early_stopping:
    enabled: true
    monitor: acc
    patience: 10
    min_delta: 0.001

  checkpoint:
    enabled: true
    monitor: acc

  reduce_lr:
    enabled: true
    monitor: loss
    factor: 0.5
    patience: 5
    min_lr: 1e-6

hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  job:
    name: train_bilstm
